package com.bjpowernode;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan({"com.bjpowernode.mapper"})
public class Springboot018MapperScanApplication {

    public static void main(String[] args) {
        SpringApplication.run(Springboot018MapperScanApplication.class, args);
    }

}
