package com.weikai;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.transaction.annotation.EnableTransactionManagement;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan({"com.weikai.mapper"})//开启mapper映射扫描器
@EnableTransactionManagement//开启事务
public class SpringbootSsm03LoginApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringbootSsm03LoginApplication.class, args);
    }

}
