#server
server:
  port: 8080
  servlet:
    context-path: /mvc11
    #解决中文乱码
    encoding:
      enabled: true
      charset: UTF-8
      force: true

#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: hsp

#mybatis
mybatis:
  configuration:
    #开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #自动驼峰映射
    map-underscore-to-camel-case: true

  #别名
  type-aliases-package: com.weikai.pojo
