#server
server:
  port: 8081
  servlet:
    context-path: /
    #编码
    encoding:
      enabled: true
      charset: UTF-8
      force: true


spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: hsp

  #  mvc:
  #    static-path-pattern: /static/**
  #配置thymeleaf  不配置还不会出错TemplateInputException
#  thymeleaf:
#    suffix: .html
#    prefix: classpath:/templates
#    mode: html



#mybatis配置
mybatis:
  configuration:
    #开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启自动驼峰映射
    map-underscore-to-camel-case: true
  #别名
  type-aliases-package: com.weikai.pojo

